{% set version = "4.1.1" %}
{% set sha256 = "e24f7a778bd11a71ad0c14587a7f5b00e68a71aa5623e2157bafee3d44c07cda" %}
{% set major = version.rpartition('.')[0] %}

package:
    name: openmpi
    version: {{ version }}

source:
    fn: openmpi-{{ version }}.tar.bz2
    url: https://www.open-mpi.org/software/ompi/v{{ major }}/downloads/openmpi-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

build:
    number: 2
{% if build_type == 'cuda' %}
    string: cuda{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }}
    script_env:
      - CUDA_HOME
{% endif %}

requirements:
    build:
        - perl 5.26.0
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
    run:
        - cudatoolkit {{ cudatoolkit }}    # [build_type == 'cuda']
        - mpi 1.0 openmpi

test:
    requires:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    files:
        - tests/helloworld.c
        - tests/helloworld.cxx

about:
    home: https://www.open-mpi.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'An open source Message Passing Interface implementation.'
    description: |
        The Open MPI Project is an open source Message Passing Interface
        implementation that is developed and maintained by a consortium of academic,
        research, and industry partners.
    doc_url: https://www.open-mpi.org/doc/
    dev_url: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
