{% set version = "4.1.4" %}
{% set sha256 = "92912e175fd1234368c8730c03f4996fe5942e7479bb1d10059405e7f2b3930d" %}
{% set major = version.rpartition('.')[0] %}

package:
    name: openmpi
    version: {{ version }}

source:
    fn: openmpi-{{ version }}.tar.bz2
    url: https://www.open-mpi.org/software/ompi/v{{ major }}/downloads/openmpi-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

build:
    number: 2
{% if build_type == 'cuda' %}
    string: {{ build_type }}{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }}
    script_env:
      - CUDA_HOME
{% else %}
    string: {{ build_type }}_{{ PKG_BUILDNUM }}
{% endif %}

requirements:
    build:
        - perl 5.26.*
        - {{ compiler('c') }}    #[ppc_arch != "p10"]
        - {{ compiler('cxx') }}  #[ppc_arch != "p10"]
        - make
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]
    host:
        # Use pins to control cos6/cos7 match
        - libgcc-ng  {{ libgcc }}         # [x86_64 and c_compiler_version == "7.2.*"]
        - libstdcxx-ng  {{ libstdcxx }}   # [x86_64 and c_compiler_version == "7.2.*"]

    run:
        - cudatoolkit {{ cudatoolkit }}    # [build_type == 'cuda']
        - mpi 1.0 openmpi
        - zlib {{ zlib }}

test:
    requires:                           #[ppc_arch != "p10"]
        - {{ compiler('fortran') }}     #[ppc_arch != "p10"]
        - {{ compiler('c') }}           #[ppc_arch != "p10"]
        - {{ compiler('cxx') }}         #[ppc_arch != "p10"]
    files:
        - tests/helloworld.c
        - tests/helloworld.cxx

about:
    home: https://www.open-mpi.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'An open source Message Passing Interface implementation.'
    description: |
        The Open MPI Project is an open source Message Passing Interface
        implementation that is developed and maintained by a consortium of academic,
        research, and industry partners.
    doc_url: https://www.open-mpi.org/doc/
    dev_url: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
