{% set version = "3.1.3" %}
{% set sha256 = "8be04307c00f51401d3fb9d837321781ea7c79f2a5a4a2e5d4eaedc874087ab6" %}
{% set major = version.rpartition('.')[0] %}

package:
    name: openmpi
    version: {{ version }}

source:
    fn: openmpi-{{ version }}.tar.bz2
    url: https://www.open-mpi.org/software/ompi/v{{ major }}/downloads/openmpi-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

build:
    number: 1
    string: cuda{{ cudatoolkit | replace(".*", "") }}_{{ PKG_BUILDNUM }}

requirements:
    build:
        - perl 5.26.0
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
    host:
        - cudatoolkit-dev {{ cudatoolkit }}
    run:
        - cudatoolkit {{ cudatoolkit }}

test:
    requires:
        - {{ compiler('fortran') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
    files:
        - tests/helloworld.c
        - tests/helloworld.cxx

about:
    home: https://www.open-mpi.org/
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: 'An open source Message Passing Interface implementation.'
    description: |
        The Open MPI Project is an open source Message Passing Interface
        implementation that is developed and maintained by a consortium of academic,
        research, and industry partners.
    doc_url: https://www.open-mpi.org/doc/
    dev_url: https://github.com/open-mpi/ompi

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
